### ISSUE TITLE
如何添加CXX支持呢

### ISSUE THREAD

**Issue by jiewen-zheng** [0x915/stm32f411-cmake#1]
我试图这样操作：
project(template C CXX ASM)  # 添加CXX

但是cmake报错：
Target: unspecified-arm-none-unspecified
	armclang: fatal error: no target architecture given; use --target=arm-arm-none-eabi or --target=aarch64-arm-none-eabi

不知道这样如何解决

**Comment by 0x915** [comment]
还需要增加对C++的编译选项和链接器命令，改的内容太多，可以看看我新提交的CMake文件

**Comment by jiewen-zheng** [comment]
非常感谢您的回复

**Comment by jiewen-zheng** [comment]
非常感谢您的回复，这个问题已经得到了解决，谢谢你"0x915"

**Comment by jiewen-zheng** [comment]
补充以下，

**Comment by jiewen-zheng** [comment]
补充一下：
在文件开头指定语言标准：set(CMAKE_CXX_STANDARD 11) set(CMAKE_C_STANDARD 99)
会在后面设置编译器选项时被覆盖：set(C_CXX_COMPILE_OPTIONS -xc -std=c99 . . .)

这会使得C++无法被正确识别（使用clion会这样，keil不会有这个问题），导致使用class等c++关键字编译报错[unknown type name 'class']

取出编译选项中的 -xc -std=c99 会解决这个问题。

**Comment by jiewen-zheng** [comment]
补充一下：
在文件开头指定语言标准：set(CMAKE_CXX_STANDARD 11) set(CMAKE_C_STANDARD 99)
会在后面设置编译器选项时被覆盖：set(C_CXX_COMPILE_OPTIONS -xc -std=c99 . . .)

这会使得C++无法被正确识别（使用clion会这样，keil不会有这个问题），导致使用class等c++关键字编译报错[unknown type name 'class']

去除编译选项中的 -xc -std=c99 会解决这个问题。

**Comment by 0x915** [comment]
好的谢谢，当时搞这个的时候是给纯C用的，写C++直接偷懒用cmake自动生成的cmake gcc
